### ISSUE TITLE
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.

### ISSUE THREAD

**Issue by avivbeeri** [eslint/typescript-eslint-parser#117]
**What version of TypeScript are you using?**
2.0.9

**What version of `typescript-eslint-parser` are you using?**
1.0.0

**What code were you trying to parse?**

_index.ts_
```
import * as express from 'express';

const app : express.Application = express();

app.get('*', (req, res) => {
  res.sendStatus(200);
});

app.listen(8080);
```

**What did you expect to happen?**

I have no problems when I use the linter-eslint package in atom, but I wanted to run eslint standalone for a build script.

Attempting to run `./node_modules/.bin/eslint --ext ts --config .eslintrc.json index.ts`

With the following .eslintrc:
```
  "env": {
    "browser": true,
    "mocha": true,
    "node": true
  },
  "parser": "typescript-eslint-parser",
  "parserOptions": {
    "ecmaVersion": 6
  },
  "extends": "defaults/configurations/airbnb/es6",
  "rules": {
    "comma-dangle": ["error", {
      "functions": "never"
    }],
    "no-empty-label": "off",
    "space-after-keywords": "off",
    "space-return-throw-case": "off",
    "no-unused-vars": "off",
    "arrow-body-style": ["error", "always"]
  }
```

**What happened?**
```
ImportDeclaration should appear when the mode is ES6 and in the module context.
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/Aviv.Beeri/development/factor-service-test/node_modules/escope/lib/referencer.js:591:34)
    at Referencer.Visitor.visit (/Users/Aviv.Beeri/development/factor-service-test/node_modules/esrecurse/esrecurse.js:122:34)
    at Referencer.Visitor.visitChildren (/Users/Aviv.Beeri/development/factor-service-test/node_modules/esrecurse/esrecurse.js:101:38)
    at Referencer.Program (/Users/Aviv.Beeri/development/factor-service-test/node_modules/escope/lib/referencer.js:419:18)
    at Referencer.Visitor.visit (/Users/Aviv.Beeri/development/factor-service-test/node_modules/esrecurse/esrecurse.js:122:34)
    at Object.analyze (/Users/Aviv.Beeri/development/factor-service-test/node_modules/escope/lib/index.js:153:16)
    at EventEmitter.module.exports.api.verify (/Users/Aviv.Beeri/development/factor-service-test/node_modules/eslint/lib/eslint.js:888:35)
    at processText (/Users/Aviv.Beeri/development/factor-service-test/node_modules/eslint/lib/cli-engine.js:264:31)
    at processFile (/Users/Aviv.Beeri/development/factor-service-test/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/Users/Aviv.Beeri/development/factor-service-test/node_modules/eslint/lib/cli-engine.js:672:25)
```

**Comment by ilyavolodin** [comment]
You are missing this section in your config:
```js
"parserOptions": {
    "sourceType": "module"
}
```
`Import/export` keywords can only be used in modules, and not scripts. By default, everything is a script, unless you specify otherwise.

**Comment by avivbeeri** [comment]
Ah, that worked. Thank you very much :)
