### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined - When parsing with rule space-before-function-paren

### ISSUE THREAD

**Issue by soda0289** [eslint/typescript-eslint-parser#123]
**What version of TypeScript are you using?**
2.0.10

**What version of `typescript-eslint-parser` are you using?**
1.0.0

**What code were you trying to parse?**

```
export class Example {
    render () {
    }
}
```

**What did you expect to happen?**
It should pass validation

**What happened?**
Uncaught Exception
```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at EventEmitter.validateSpacingBeforeParentheses (/usr/lib/node_modules/eslint/lib/rules/space-before-function-paren.js:128:30)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/usr/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/usr/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/usr/lib/node_modules/eslint/lib/eslint.js:925:36)
    at Controller.__execute (/usr/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/usr/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/usr/lib/node_modules/eslint/lib/util/traverser.js:36:33)
```

Eslint file
```
{
    "parser": "typescript-eslint-parser",
    "rules": {
        "space-before-function-paren": [
            "error",
            "always"
        ]
    }
}

```

**Comment by soda0289** [comment]
Seems like babel-eslint has same problem:
https://github.com/eslint/eslint/issues/4581
https://github.com/eslint/eslint/issues/4575

**Comment by monolithed** [comment]
I still see these errors:

```
/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/rules/space-before-function-paren.js:128
            while (rightToken.value !== "(") {
                             ^

TypeError: Cannot read property 'value' of undefined
    at EventEmitter.validateSpacingBeforeParentheses (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/rules/space-before-function-paren.js:128:30)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/a.abashkin/workspace/mail.ru/e.mail.ru/tests/node_modules/eslint/lib/util/traverser.js:36:33)
npm ERR! Test failed.  See above for more details.

```

**Comment by JamesHenry** [comment]
@monolithed On what TypeScript version and what version of typescript-eslint-parser?

**Comment by monolithed** [comment]
@JamesHenry, it seems the problem is not actual in 1.0.3
