### ISSUE TITLE
Cannot make a constructor public

### ISSUE THREAD

**Issue by aboyton** [eslint/typescript-eslint-parser#151]
**What version of TypeScript are you using?**
2.0.10

**What version of `typescript-eslint-parser` are you using?**
1.0.2

**What code were you trying to parse?**

```typescript
export class Test {
  public constructor() {}
}
```

**What did you expect to happen?**
The code to parse. If I remove the word in `public` it parses correctly. (I do realise that adding `public` doesn't really do anything, but the linter shouldn't crash when it tries to parse it.)

**What happened?**

I got the following console error.

```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at EventEmitter.validateSpacingBeforeParentheses (/Volumes/foo/node_modules/eslint/lib/rules/space-before-function-paren.js:128:30)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Volumes/foo/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Volumes/foo/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Volumes/foo/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Volumes/foo/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Volumes/foo/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Volumes/foo/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Volumes/foo/node_modules/eslint/lib/util/traverser.js:36:33)
    at EventEmitter.string.split.forEach.string.split.forEach.Object.keys.forEach.Object.keys.forEach.Object.keys.forEach.Object.keys.forEach.globalScope.through.rulesToDisable.forEach.rulesToEnable.forEach.ast.comments.forEach.Object.keys.forEach.Object.keys.forEach.Object.keys.forEach.module.exports.api.verify.Object.keys.filter.key.forEach.key [as verify] (/Volumes/foo/node_modules/eslint/lib/eslint.js:925:23)
    at processText (/Volumes/foo/node_modules/eslint/lib/cli-engine.js:264:31)
    at processFile (/Volumes/foo/node_modules/eslint/lib/cli-engine.js:303:18)
    at executeOnFile (/Volumes/foo/node_modules/eslint/lib/cli-engine.js:672:25)
    at /Volumes/foo/node_modules/eslint/lib/cli-engine.js:710:13
    at Array.forEach (native)
```

**Comment by soda0289** [comment]
Should be fixed in master by https://github.com/eslint/typescript-eslint-parser/commit/6312383d2013285b55f310b5722c7728fbb7ef76

**Comment by JamesHenry** [comment]
@aboyton Please try the new release, `1.0.3`, and let us know if you have any problems.
