### ISSUE TITLE
Await node should have argument property not expression property

### ISSUE THREAD

**Issue by soda0289** [eslint/typescript-eslint-parser#160]
Typescript: 2.1.6
Typescript-Eslint-Parser: ts-2.1
Eslint: v3.15.0

Code:
```ts
/* eslint no-extra-parens: error */
async function foo() {
    await 3;
}
```

**What did you expect to happen?**
Should parse

**What happened?**
Exception
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at ruleApplies (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\rules\no-extra-parens.js:78:21)
    at hasExcessParens (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\rules\no-extra-parens.js:128:20)
    at EventEmitter.dryUnaryUpdate (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\rules\no-extra-parens.js:374:17)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Controller.enter (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:928:36)
    at Controller.__execute (C:\Users\reyad.attiyat\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
```

The await node should have an argument property not an expression property. Will submit PR.

**Comment by soda0289** [comment]
Estree definition:
https://github.com/estree/estree/blob/master/es2017.md
