### ISSUE TITLE
Error parsing JSX with newlines (cannot read property 'type' of null=

### ISSUE THREAD

**Issue by andersekdahl** [eslint/typescript-eslint-parser#170]
**What version of TypeScript are you using?**
2.1.6

**What version of `typescript-eslint-parser` are you using?**
1.0.3

**What version of `eslint` are you using?**
3.16.1

**My .eslintrc.json**
```
{
    "extends": "eslint:recommended",
    "parser": "typescript-eslint-parser",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true
        }
    }
}
```

**What code were you trying to parse?**

```
export default (props: Props) => (
  <Main appearance="narrow" className={styles.base}>
  </Main>
);
```

**What did you expect to happen?**
Should be able to parse it.

**What happened?**
Got this error:
```
> eslint file.tsx
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at EventEmitter.Literal (C:\path\node_modules\eslint\lib\rules\no-empty-character-class.js:49:26)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (C:\path\node_modules\eslint\lib\util\node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (C:\path\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (C:\path\node_modules\eslint\lib\util\comment-event-generator.js:98:23)
    at Controller.enter (C:\path\node_modules\eslint\lib\eslint.js:928:36)
    at Controller.__execute (C:\path\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\path\node_modules\estraverse\estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (C:\path\node_modules\eslint\lib\util\traverser.js:36:33)
```

Changing the code to this:
```
export default (props: Props) => (
  <Main appearance="narrow" className={styles.base}></Main>
);
```
Seems to make the error go away and I get warnings as expected.

**Comment by JamesHenry** [comment]
@andersekdahl Please try this on master, the JSX fix has not yet been released to npm

**Comment by andersekdahl** [comment]
Ah, sorry! I'll try it out.

**Comment by JamesHenry** [comment]
We have just released version `2.0.0` on npm.

Please let me know if you still have the issue with that!

**Comment by evollu** [comment]
I have similar issue
I get `Cannot read property 'type' of undefined` on tsx files. ts file runs fine

Typescript 2.2.1
using Eslint plugin

**Comment by soda0289** [comment]
@evollu Can you narrow down the code exactly. This could be another unrelated issue. The code posted above works as I have just tested it on TS 2.2.1 Parser 2.0.0. and ESLint 3.16.1

**Comment by JamesHenry** [comment]
@evollu For clarity please open a new issue with full source code and ESLint config details.

Thanks for confirming this issue has been resolved @soda0289, I am going to close it
