### ISSUE TITLE
Type Casting appears to consistently cause errors

### ISSUE THREAD

**Issue by low-ghost** [eslint/typescript-eslint-parser#20]
I'm using eslint 2.2 and this repo from master. It seems like several rules thow errors due to type casting.

For instance this code:
```js
<any>sinon.stub()
```
results in this stack trace:
```sh
...some removed things.../node_modules/eslint/lib/rules/key-spacing.js:242
            property.key.range[1], property.value.range[0]
                                                 ^

TypeError: Cannot read property 'range' of null
    at getPropertyWhitespace (...some removed things.../node_modules/eslint/lib/rules/key-spacing.js:242:50)
    at verifySpacing (...some removed things.../node_modules/eslint/lib/rules/key-spacing.js:333:22)
    at EventEmitter.Property (...some removed things.../node_modules/eslint/lib/rules/key-spacing.js:373:17)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (...some removed things.../node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (...some removed things.../node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (...some removed things.../node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (...some removed things.../node_modules/eslint/lib/eslint.js:839:36)
    at Controller.__execute (...some removed things.../node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (...some removed things.../node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
```
while removing the casting (and jumping through a few typescript hoops) allows the linter to execute and report normal errors. Can give more info if it'd be helpful. Thanks!

**Comment by low-ghost** [comment]
on other occasions, different rules have thrown, presumably before this one and due to an underlying problem with the AST.

**Comment by nzakas** [comment]
Type casting is not yet supported by this parser, so this is expected.

**Comment by nzakas** [comment]
Please see https://github.com/eslint/typescript-eslint-parser/issues/13 for the development plan.
