### ISSUE TITLE
npm run test => error

### ISSUE THREAD

**Issue by Aladdin-ADD** [eslint/typescript-eslint-parser#211]
If there is a configuration file in the parent directory, like this
```js
{
"extends": "eslint:recommended",
"parser": "babel-eslint"
}
```
`npm run test` output errors:
```bash
> node Makefile.js test

Validating Makefile.js
Cannot find module 'babel-eslint'
Error: Cannot find module 'babel-eslint'
    at Object.resolve (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at Object.load (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/config/config-file.js:518:42)
    at loadConfig (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/config.js:227:22)
    at processText (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/cli-engine.js:223:27)
    at processFile (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/cli-engine.js:298:18)
    at executeOnFile (/Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/cli-engine.js:682:23)
    at /Users/zsd/repo/typescript-eslint-parser/node_modules/eslint/lib/cli-engine.js:719:13
    at Array.forEach (native)
Validating JavaScript files
```
Is this expected? thanks in advance for your kindly response. 😄

**Comment by soda0289** [comment]
I'm not sure if eslint is supposed to load a configuration file from a parent directory when it find one in the current directory. Will look into this tonight.

**Comment by platinumazure** [comment]
@soda0289 @Aladdin-ADD ESLint will continue to search parent directories for configurations until it finds one with `"root": true` in it. Best practice is to mark the configuration at the root of your project with `"root": true`.

**Comment by soda0289** [comment]
@platinumazure Thanks. Will be an easy fix.
