### ISSUE TITLE
Typescript finds comment inside of template string

### ISSUE THREAD

**Issue by bradzacher** [eslint/typescript-eslint-parser#216]
**What version of TypeScript are you using?**
2.2.1

**What version of `typescript-eslint-parser` are you using?**
2.1.0

**What code were you trying to parse?**
```JS
const str = `${__dirname}/test/*.js`;

module.exports = str;
```

**What happened?**
```
Cannot read property 'loc' of null
TypeError: Cannot read property 'loc' of null
    at getNodeIndent (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/rules/indent.js:328:71)
    at checkNodeIndent (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/rules/indent.js:363:34)
    at nodes.forEach.node (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/rules/indent.js:411:35)
    at Array.forEach (native)
    at checkNodesIndent (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/rules/indent.js:411:19)
    at EventEmitter.Program (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/rules/indent.js:975:21)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/bradzacher/.config/yarn/global/node_modules/eslint/lib/util/node-event-generator.js:294:22)
```

note that these files seem to work fine, which leads me to believe it's a problem with the asterisk in the template string.
```JS
const str = `${__dirname}`;

module.exports = str;
```
```JS
const str = `${__dirname}/asdf.js`;

module.exports = str;
```

**Comment by soda0289** [comment]
I was able to reproduce this problem. It seems to not be present in v4 alpha of eslint indent rule. Looks like when we try and find the first token of the expressions statement `module.exports = str;` it return null instead of `module`. Will investigate more, thanks for the info.

**Comment by soda0289** [comment]
Temporary workaround is to downgrade to eslint version 3.15.0. 

There was an upgrade to the eslint token-store that will skip over tokens enclosed in a comment. It seems typescript parer thinks that everything after the `/*` is a comment. This likely explains this other issue: #215. I have a feeling this is a bug in typescript since changing the template string to a single/double quoted string fixes the issue.

**Comment by soda0289** [comment]
I have opened a typescript issue:
https://github.com/Microsoft/TypeScript/issues/15115

**Comment by soda0289** [comment]
Looks like this is not a bug in typescript but a misuse of the typescript scanner. We need a better way to find comments. I have started one solution but need to spend more time finding one that covers all cases. Will post fix soon.
