### ISSUE TITLE
Cannot read property 'expression' of undefined

### ISSUE THREAD

**Issue by vjeux** [eslint/typescript-eslint-parser#249]
There are two tests in the typescript codebase that make typescript-eslint-parser throw:

```js
../TypeScript/tests//cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause1.ts: TypeError: Cannot read property 'expression' of undefined
    at convert (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:1580:79)
```

```js
../TypeScript/tests//cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause3.ts: TypeError: Cannot read property 'expression' of undefined
    at convert (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:1580:79)
    at convertChild (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:501:20)
    at /Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:746:46
    at Array.forEach (native)
    at convert (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:745:33)
    at module.exports (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/lib/ast-converter.js:2089:18)
    at Object.parse (/Users/despairblue/git/prettier/node_modules/typescript-eslint-parser/parser.js:239:12)
    at parseWithTypeScript (/Users/despairblue/git/prettier/src/parser.js:58:17)
    at parse (/Users/despairblue/git/prettier/index.js:32:12)
    at format (/Users/despairblue/git/prettier/index.js:80:15)
    at formatWithShebang (/Users/despairblue/git/prettier/index.js:91:12)
    at Object.format (/Users/despairblue/git/prettier/index.js:105:12)
```

Was found in https://github.com/prettier/prettier/issues/1480

Those are the only two crashes from typescript-eslint-parser of the entire run: https://gist.githubusercontent.com/despairblue/79e090660fbb4093b35ab3b24c617dfb/raw/99e47ad1e34c32ddd91c15315f3c4fb92fa37d65/errors

**Comment by soda0289** [comment]
Thanks for the report.

Do you have some sample code that can reproduce the problem? I'm having a hard time understanding the output you posted

**Comment by vjeux** [comment]
Sorry it was confusing, those two files are triggering it:

https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause3.ts
https://github.com/Microsoft/TypeScript/blob/master/tests/cases/conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause1.ts

**Comment by soda0289** [comment]
@vjeux Thanks. 

I did not know extend could be empty, you would think the typescript parser would complain about this. Will fix this case later today.

**Comment by vjeux** [comment]
This looks like it's in "ErrorRecovery" directory, so typescript is trying to be lenient around those things.

**Comment by vjeux** [comment]
The good thing is that this is the only error triggered by this project when running against all the 11k files of the typescript test suite :)

**Comment by JamesHenry** [comment]
That is fantastic news, thanks again for running those tests!
