### ISSUE TITLE
Maximum call stack size exceeded when using eslint 4 indent rule

### ISSUE THREAD

**Issue by bluetech** [eslint/typescript-eslint-parser#333]
**What version of TypeScript are you using?**

- typescript@2.3.4

**What version of `typescript-eslint-parser` are you using?**

- eslint@4.1.1
- typescript-eslint-parser@3.0.0

Here is a reduced .eslintrc.json:

```
{
    "parser": "typescript-eslint-parser",
    "rules": {
        "indent": ["error"]
    }
}
```

**What code were you trying to parse?**

Here is the reduced code (as much as I manged):

```
class a {
    /** @b {} c */
    d = e => {}
}
```

**What did you expect to happen?**

Don't crash!

**What happened?**

```
$ ./node_modules/.bin/eslint x.ts 
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at WeakSet.has (native)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:334:36)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
    at OffsetStorage.getDesiredIndent (node_modules/eslint/lib/rules/indent.js:352:103)
$
```

Thanks! I hope it's not a duplicate. With eslint 3 this does not happen.

**Comment by soda0289** [comment]
Thanks for the report. I can reproduce this problem.

**Comment by JamesHenry** [comment]
I was no longer able to reproduce this. Please feel free to reopen if it is still an issue
