### ISSUE TITLE
npm seems to give me either an old version or a broken version

### ISSUE THREAD

**Issue by DanielCollins** [eslint/typescript-eslint-parser#37]
Forgive me if this is user error or expected behavior; I am new to npm.

I originally had `"typescript-eslint-parser": "0.1.0-alpha-1"` in `package.json`, but, examining the contents of  `node_modules/typescript-eslint-parser/parser.js` showed that the version looked old and did not include the recent about JSX syntax, which `typescript-eslint-parser-0.1.0-alpha.1.zip` from github  did include. Eventually I realised the difference is the `.` instead of `-` after `alpha`. Confusing.

Changing to `"typescript-eslint-parser": "0.1.0-alpha.1"` in `package.json`, seems to make it install a newer version, however i get this stack trace when invoking eslint, with typescript-eslint-parser configured as the parser:

    TypeError: Cannot read property 'loc' of undefined
        at getNodeIndent (node_modules/eslint/lib/rules/indent.js:219:54)
        at checkNodeIndent (node_modules/eslint/lib/rules/indent.js:248:30)
        at node_modules/eslint/lib/rules/indent.js:272:17
        at Array.forEach (native)
        at checkNodesIndent (node_modules/eslint/lib/rules/indent.js:266:19)
        at EventEmitter.Program (node_modules/eslint/lib/rules/indent.js:706:21)
        at emitOne (events.js:101:20)
        at EventEmitter.emit (events.js:188:7)
        at NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:40:22)
        at CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)

**Comment by nzakas** [comment]
This project is still in the experimental phase and is not guaranteed to work. Only a small subset of functionality works, basically only strict ES6 syntax. It's not worth tracking bugs until threads a reasonable expectation that the functionality is complete.
