### ISSUE TITLE
Typescript parser for eslint causing error in eslint-plugin-react.

### ISSUE THREAD

**Issue by dmi3y** [eslint/typescript-eslint-parser#379]
**What version of TypeScript are you using?**
^2.4.2

**What version of `typescript-eslint-parser` are you using?**
^7.0.0

**What code were you trying to parse?**

```
import React from 'react'

export default class Test extends React.PureComponent {
  render () {
    return <div>
      <div>
        Breaks
      </div>
    </div>
  }
}
```

**What did you expect to happen?**
Linter passing

**What happened?**
```
Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Linter.JSXOpeningElement (/typescript-eslint/node_modules/eslint-plugin-react/lib/rules/jsx-indent.js:229:32)
    at emitOne (events.js:120:20)
    at Linter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/typescript-eslint/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/typescript-eslint/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/typescript-eslint/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/typescript-eslint/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at Traverser.enter (/typescript-eslint/node_modules/eslint/lib/linter.js:925:36)
    at Traverser.__execute (/typescript-eslint/node_modules/estraverse/estraverse.js:397:31)
    at Traverser.traverse (/typescript-eslint/node_modules/estraverse/estraverse.js:501:28)
```

Minimal reproducible example [here](https://github.com/dmi3y/typescript-eslint-bugreport)

**Comment by ismail-syed** [comment]
@dmi3y, Have you tried https://github.com/eslint/typescript-eslint-parser/issues/210#issuecomment-291643534

**Comment by dmi3y** [comment]
Hey @ismail-syed thanks for suggestion! I have not, ended up using tslint instead. I might try return to eslint if it will work.

**Comment by JamesHenry** [comment]
This doesn't appear to still be an issue, please feel free to reopen if you can reproduce with the latest version of the parser and currently supported stable version of TypeScript.
