### ISSUE TITLE
Tests fail because of espree not being available

### ISSUE THREAD

**Issue by JamesHenry** [eslint/typescript-eslint-parser#6]
I was simply trying to put together a PR to address https://github.com/eslint/typescript-eslint-parser/issues/2, but the tests are unable to run because of espree not being available in the project.

All I did was fork the repo and run `npm t`

```
npm t

> typescript-eslint-parser@0.1.0-alpha-1 test /Users/james/Sites/typescript-eslint-parser
> node Makefile.js test

No coverage information was collected, exit without writing coverage information
module.js:338
    throw err;
    ^

Error: Cannot find module '../../espree'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/james/Sites/typescript-eslint-parser/tests/lib/attach-comments.js:36:14)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.Module._extensions..js (/Users/james/Sites/typescript-eslint-parser/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

...ETC...
```

**Comment by JamesHenry** [comment]
Whilst this is a simple enough error, I am unclear as to whether the dependency is missing, or whether the seeming requirement for it is erroneous (as is the case for #2)

**Comment by nzakas** [comment]
It shouldn't be required, that's definitely a mistake.

**Comment by nzakas** [comment]
Okay, basic tests should be fixed. I don't have all of the ones we'll need eventually, but this should at least unblock further development.

**Comment by JamesHenry** [comment]
Thanks a lot! Just to confirm, is this fixed in the sense of being runnable, or also passing?

Look forward to contributing more to this over the coming weeks!

**Comment by nzakas** [comment]
Runnable. See https://github.com/eslint/typescript-eslint-parser/issues/15. Would love since help on that.
